"use client";
import Button from "@mui/material/Button";
import Paper from "@mui/material/Paper";
import { ArrowDownLeft, ArrowUpRight, MoreHorizontal, Pencil, Trash2, Wallet } from "lucide-react";
import type { Source, Category, Transaction } from "./finance-types";
import { formatMoney, formatDate } from "./finance-utils";

export function Stat({ title, amount, icon, note }: { title: string; amount: number; icon: "income" | "expense"; note: string }) { return <Paper elevation={0} className="stat-card"><div className={`stat-icon ${icon}`}>{icon === "income" ? <ArrowDownLeft size={21}/> : <ArrowUpRight size={21}/>}</div><div className="stat-title">{title}</div><div className="stat-amount">{formatMoney(amount)}</div><div className="stat-note">{note}</div></Paper>; }
export function TransactionTable({ rows, categories, sources, onClick }: { rows: Transaction[]; categories: Category[]; sources: Source[]; onClick: (t: Transaction) => void }) { return <Paper elevation={0} className="table-card"><div className="table-head"><span>TRANSACTION</span><span>CATEGORY</span><span>DATE</span><span>AMOUNT</span><span/></div>{rows.length === 0 ? <div className="empty-state"><div className="empty-icon"><Wallet size={27}/></div><h3>Nothing here yet</h3><p>Your transactions will show up here as soon as you add one.</p></div> : rows.map(t => <Button className="table-row" key={t.id} onClick={() => onClick(t)}><span className="transaction-main"><span className={`transaction-icon ${t.kind}`}>{t.kind === "income" ? <ArrowDownLeft size={20}/> : <ArrowUpRight size={20}/>}</span><span><strong>{t.description}</strong><small>{sources.find(s => s.id === t.source_id)?.name || "No source"}</small></span></span><span className="category-cell">{categories.find(c => c.id === t.category_id)?.name || "Uncategorized"}</span><span className="date-cell">{formatDate(t.occurred_on)}</span><span className={`amount-cell ${t.kind}`}>{t.kind === "expense" ? "−" : "+"}{formatMoney(t.amount_minor, t.currency)}</span><MoreHorizontal size={18} className="more-icon"/></Button>)}</Paper>; }
export function CategorySection({ title, kind, categories, onDelete, onEdit }: { title: string; kind: "income" | "expense"; categories: Category[]; onDelete: (id: string) => void; onEdit: (item: Category) => void }) { const items = categories.filter(c => c.kind === kind); return <Paper elevation={0} className="list-card"><div className="list-card-heading"><div className={`small-round ${kind}`}>{kind === "income" ? <ArrowDownLeft size={18}/> : <ArrowUpRight size={18}/>}</div><h3>{title}</h3><span>{items.length}</span></div>{items.length === 0 ? <p className="list-empty">No categories yet. Add one to get organized.</p> : items.map(c => <div className="category-row" key={c.id}><span className="color-dot" style={{ background: c.color }}/><span style={{ paddingLeft: c.parent_id ? 18 : 0 }}>{c.name}{c.parent_id && <small>under {categories.find(p => p.id === c.parent_id)?.name}</small>}</span><Button className="icon-button" onClick={() => onEdit(c)} aria-label={`Edit ${c.name}`}><Pencil size={15}/></Button><Button className="icon-button" onClick={() => onDelete(c.id)} aria-label={`Delete ${c.name}`}><Trash2 size={15}/></Button></div>)}</Paper>; }
